### ISSUE TITLE
New repo for "Data Coordinator"

### ISSUE THREAD

**Issue by dasBikash84** [dasBikash84/NewsServer_reloaded_master#20]
### Tasks:

- [x] Create new java maven project for data coordinator
- [x] Create mysql database for the project
- [x] Create new repository and upload init commit
