### ISSUE TITLE
Finalize coordinator app

### ISSUE THREAD

**Issue by dasBikash84** [dasBikash84/NewsServer_reloaded_master#21]
### Final goals:

- **For now it will be a console application.**
- **Top level main method will basically do three things**
      a) Fetch and merge settings from parser.
      b) Operate article fetcher.
      c) Operate article up-loaders.
- **Proper logging of all events**
- **REST service providing access to log,status and operation of modules.**

**Comment by dasBikash84** [comment]
### Tasks:
@[coordinator_app](https://github.com/dasBikash84/news_server_data_coordinator)

- [ ] Define top level coordinator class
- [ ] Identify points, list and sought out handling procedures for exceptions.
- [ ] Modify database and add model required model classes for exception logging.
- [ ] Define exception classes and add "throw" at appropriate points.
- [ ] Define exception handlers with proper logging.

@[coordinator_rest_app](https://github.com/dasBikash84/ns_reloaded_spring_mvc_rest_end)

- [ ] Identify and make detail list of REST service end points data requirement. 
- [ ] Modify database if required.
- [ ] Implement end points.
