### ISSUE TITLE
Add delete rest end points to Data Coordinator Rest Service

### ISSUE THREAD

**Issue by dasBikash84** [dasBikash84/NewsServer_reloaded_master#24]
### Tasks:

- [x] Add rest end points  for General Log entries delete.
- [x] Add rest end points  for Error Log entries delete.
- [x] Add rest end points  for Article Download Log entries delete.
- [x] Add rest end points  for Article Upload Log entries delete.
- [x] Add rest end points  for Settings Update Log entries delete.
- [x] Add rest end points  for Settings Upload Log entries delete.
