### ISSUE TITLE
Add rest end points for log entities of Parser Rest Service

### ISSUE THREAD

**Issue by dasBikash84** [dasBikash84/NewsServer_reloaded_master#25]
### Tasks:

- [x] Add rest end points for General Log entries
- [x] Add rest end points for Exception Log entries
- [x] Add rest end points for page_parsing_history Log entries
- [x] Add rest end points for page_groups entries
